### ISSUE TITLE
Generating a JWT for responses

### ISSUE THREAD

**Issue by Poimen** [MasonM/wiremock-jwt-extension#11]
Hi,

This plugin seems to cater for an incoming jwt matching and responses based on the jwt.

The test we want to do is for the typical login flow - go to a url, get a jwt, wait for the jwt to expire and test that the code grabs a new jwt.

Is this something that can be done with this plugin?

If not, could this be a scenario that could be considered to be added to the plugin?

Thanks.

**Comment by MasonM** [comment]
I'm not clear on what you're looking for. Do you want a [response transformer](https://wiremock.org/docs/extending-wiremock/#transforming-responses) that can dynamically generate a JWT? I guess that's something this extension could do, but I don't know the use case for that functionality.

**Comment by Poimen** [comment]
Yes, essentially transform the response to produce a time bound jwt.

So my particular use case is to simulate a login scenario. So we have scenario where we want to time bound the jwt to a minute then the service should grab a new jwt when it expires.

We are using this more as a local development environment as the real one is behind a VPN. We mock the different endpoints, each of which requires the jwt to be present. If expired, return 401 else return mock data.

We could run a jwt server locally and use wiremock to proxy to it, but thought it might be nice to have this in one plugin?

**Comment by MasonM** [comment]
I don't think you need a separate plugin for that. The existing [Response Templating](https://wiremock.org/docs/response-templating/) functionality will let you dynamically generate tokens in the response. Here's an example request that creates a stub mapping for an unsecured JWT that expires in 3 days:
```
curl -d@- http://localhost:8080/__admin/mappings <<-EOD
{
    "request" : {
        "url" : "/some_url"
    },
    "response" : {
        "body": "{{#base64}}{\"type\":\"JWT\",\"alg\":\"none\"}{{/base64}}.{{#base64}}{\"exp\":{{now offset='3 days' format='epoch'}} }{{/base64}}",
        "transformers": ["response-template"]
    }
}
EOD
```

Generating a signed JWT is a bit trickier since you'll need a Handlebars helper to generate the signature. The docs say you can register a custom helper with Java, but I haven't tried that before.

**Comment by Poimen** [comment]
Thankfully we're not validating the jwt 😀

I'll give it a try when I get back to my desk 👍

**Comment by Poimen** [comment]
This worked nicely, with a few changes - 

Just in case someone trips over this, I missed that you need to enable response templating, so start wiremock with command line parameter `--local-response-templating` in order for the response templating to be enabled.

Then, created a mapping:
```json
{
  "request": {
      "urlPath": "/templated"
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json"
    },
    "bodyFileName": "templated.json",
    "transformers": ["response-template"]
  }
}
```

and a file based response:
```
{
  "token": "{{#base64}}{"alg":"none", "type": "JWT"}{{/base64}}.{{#base64}}{"sub":"ARCH","AUTHORITIES":"SYSTEM","iat":1652285024,"exp":{{now format='unix'}} }{{/base64}}"
}
```

So the template does not escape the `"` in the base64 and timestamp is `unix` (jwt.io validates the time as unix)


Thanks for the support 👍
