### ISSUE TITLE
WireMock 3 compatibility

### ISSUE THREAD

**Issue by petrandreev** [MasonM/wiremock-jwt-extension#13]
As mentioned in https://github.com/wiremock/wiremock/issues/2323
it would be nice to have extension compatible with WireMock 3
(dropping support for Java 8, etc.)

**Comment by petrandreev** [comment]
Hi Mason,
the  Sonatype repo looks OK, I believe,
<img width="1494" alt="image" src="https://github.com/MasonM/wiremock-jwt-extension/assets/5670574/19c07c94-9b5d-420f-ba58-12b42fd25ca1">

but I think, the promotion to release repo is needed:
https://central.sonatype.org/publish/release/#locate-and-examine-your-staging-repository

**Comment by MasonM** [comment]
@petrandreev Thanks for the reminder. It should be fully released now.
